#! /bin/sh

echo 0 > /sys/class/pwm/pwmchip1/export 
echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable 1
echo 5000000 > /sys/class/pwm/pwmchip1/pwm0/period 
echo 4800000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle 
